#!/bin/sh

PORT="5155"
APP_DIR="/home/pi/Dev/python/EosPython"
DAEMON_NAME="eosudpd"
PYTHON_APP="udpd"
PID_DIR="/var/run"
PID_FILE="$PID_DIR/$DAEMON_NAME.pid"
LOG_DIR="/var/log"
LOG_FILE="$LOG_DIR/$DAEMON_NAME.log"
PYTHON_EXEC=$(which python)

###############

# REDHAT chkconfig header

# chkconfig: - 58 74
# description: eosserver is the script for starting a $DAEMON_NAME on boot.
### BEGIN INIT INFO
# Provides: eosudpd
# Required-Start:    $network $remote_fs $local_fs
# Required-Stop:     $network $remote_fs $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start and stop eos tcp socket server
# Description: Eos udp server
### END INIT INFO

###############

USAGE="Usage: $0 {start|stop|restart|status} [--force]"
FORCE_OP=true

pid_file_exists() {
    [ -f "$PID_FILE" ]
}

get_pid() {
    echo "$(cat "$PID_FILE")"
}

is_running() {
    PID=$(get_pid)
    ! [ -z "$(ps aux | awk '{print $2}' | grep "^$PID$")" ]
}

start_it() {
    mkdir -p "$PID_DIR"
    mkdir -p "$LOG_DIR"

    echo "Starting $DAEMON_NAME ..."
    PORT="$PORT" $PYTHON_EXEC "$APP_DIR/$PYTHON_APP"  1>"$LOG_FILE" 2>&1 &
    echo $! > "$PID_FILE"
    echo "$DAEMON_NAME started with pid $!"
}

stop_process() {
    PID=$(get_pid)
    echo "Killing process $PID"
    kill $PID
}

remove_pid_file() {
    echo "Removing pid file"
    rm -f "$PID_FILE"
}

start_app() {
    if pid_file_exists
    then
        if is_running
        then
            PID=$(get_pid)
            echo "$DAEMON_NAME already running with pid $PID"
            exit 1
        else
            echo "$DAEMON_NAME stopped, but pid file exists"
            if [ $FORCE_OP = true ]
            then
                echo "Forcing start anyways"
                remove_pid_file
                start_it
            fi
        fi
    else
        start_it
    fi
}

stop_app() {
    if pid_file_exists
    then
        if is_running
        then
            echo "Stopping $DAEMON_NAME ..."
            stop_process
            remove_pid_file
            echo "$DAEMON_NAME stopped"
        else
            echo "$DAEMON_NAME already stopped, but pid file exists"
            if [ $FORCE_OP = true ]
            then
                echo "Forcing stop anyways ..."
                remove_pid_file
                echo "$DAEMON_NAME stopped"
            else
                exit 1
            fi
        fi
    else
        echo "$DAEMON_NAME already stopped, pid file does not exist"
        exit 1
    fi
}

status_app() {
    if pid_file_exists
    then
        if is_running
        then
            PID=$(get_pid)
            echo "$DAEMON_NAME running with pid $PID"
        else
            echo "$DAEMON_NAME stopped, but pid file exists"
        fi
    else
        echo "$DAEMON_NAME stopped"
    fi
}

case "$2" in
    --force)
        FORCE_OP=true
    ;;

    "")
    ;;

    *)
        echo $USAGE
        exit 1
    ;;
esac

case "$1" in
    start)
        start_app
    ;;

    stop)
        stop_app
    ;;

    restart)
        stop_app
        start_app
    ;;

    status)
        status_app
    ;;

    *)
        echo $USAGE
        exit 1
    ;;
esac
